"""Modular Aider AI Agent Adapter."""

from __future__ import annotations

from .base import BaseAgentAdapter


class AiderAdapter(BaseAgentAdapter):
    name = "aider"
    config_relpath = ".aider.conf.yml"

    def generate_config_content(self) -> str:
        return """# .aider.conf.yml generated by captain-hook
auto-lint: true
lint-cmd: "captain-hook dispatch PostWrite"
auto-test: true
test-cmd: "python3 -m unittest discover tests"
"""
